apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      initContainers:
        - command:
            - /bin/sh
            - -exc
            - |
              echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
              STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
              if test $STATUSCODE -ne 200; then
                  echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
                  exit 1
              fi
          name: frontend-check
          image: busybox:latest
          env:
            - name: FRONTEND_ADDR
              value: "nginx-web-server:8080"
      containers:
        - name: main
          # image: meghnapancholi/mm-loadgenerator:latest1
          image: meghnapancholi/mm-loadgenerator:latest-warmup
          imagePullPolicy: Always
          env:
            - name: FRONTEND_ADDR
              value: "nginx-web-server:8080"
            - name: RPS
              value: "200"
            - name: NUM_THREADS
              value: "10"
            - name: NUM_CONNECTIONS
              value: "10"
            - name: DURATION
              value: "300"
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
