configMaps:
- mountPath: /media-microservices/config/jaeger-config.yml
  name: jaeger-config.yml
  value: jaeger-config
- mountPath: /media-microservices/config/service-config.json
  name: service-config.json
  value: service-config
container:
  env:
  - name: COLLECTOR_ZIPKIN_HTTP_PORT
    value: 9411
  - name: EXTRA_LATENCY
    value: 0ms
  image: jaegertracing/all-in-one
  imageVersion: 1.6
  name: jaeger
  ports:
  - containerPort: 5775
    protocol: UDP
  - containerPort: 6831
    protocol: UDP
  - containerPort: 6832
    protocol: UDP
  - containerPort: 5778
  - containerPort: 16686
  - containerPort: 14268
  - containerPort: 9411
name: jaeger
ports:
- port: 5775
  protocol: UDP
  targetPort: 5775
- port: 6831
  protocol: UDP
  targetPort: 6831
- port: 6832
  protocol: UDP
  targetPort: 6832
- port: 5778
  targetPort: 5778
- port: 16686
  targetPort: 16686
- port: 14268
  targetPort: 14268
- port: 9411
  targetPort: 9411
