name: movie-id-service

ports:
  - port: 9090
    targetPort: 9090

container:
  command: MovieIdService
  image: meghnapancholi/dsb-media
  imageVersion: sleeps
  name: movie-id-service
  ports:
    - containerPort: 9090
  extraLatencyMs: 0

configMaps:
  - name: jaeger-config.yml
    mountPath: /media-microservices/config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /media-microservices/config/service-config.json
    value: service-config
